resource: 'google_netapp_kmsconfig'
generation_type: 'mmv1'
source_file: 'products/netapp/kmsconfig.yaml'
api_service_name: 'netapp.googleapis.com'
api_version: 'v1'
api_resource_type_kind: 'KmsConfig'
fields:
  - field: 'crypto_key_name'
  - field: 'description'
  - field: 'effective_labels'
    provider_only: true
  - field: 'instructions'
  - field: 'labels'
  - field: 'location'
    provider_only: true
  - field: 'name'
    provider_only: true
  - field: 'service_account'
  - field: 'terraform_labels'
    provider_only: true
