resource: google_netapp_kmsconfig
generation_type: mmv1
source_file: products/netapp/kmsconfig.yaml
api_service_name: netapp.googleapis.com
api_version: v1
api_resource_type_kind: KmsConfig
fields:
    - api_field: cryptoKeyName
    - api_field: description
    - field: effective_labels
      provider_only: true
    - api_field: instructions
    - api_field: labels
    - field: location
      provider_only: true
    - field: name
      provider_only: true
    - api_field: serviceAccount
    - field: terraform_labels
      provider_only: true
