resource: 'google_scc_v2_project_notification_config'
generation_type: 'mmv1'
source_file: 'products/securitycenterv2/ProjectNotificationConfig.yaml'
api_service_name: 'securitycenter.googleapis.com'
api_version: 'v2'
api_resource_type_kind: 'NotificationConfig'
api_variant_patterns:
  - 'projects/{project}/locations/{location}/notificationConfigs/{notificationConfig}'
fields:
  - field: 'config_id'
    provider_only: true
  - api_field: 'description'
  - field: 'location'
    provider_only: true
  - api_field: 'name'
  - api_field: 'pubsubTopic'
  - api_field: 'serviceAccount'
  - api_field: 'streamingConfig.filter'
