# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

resource: 'google_apigee_sharedflow_deployment'
generation_type: 'handwritten'
api_service_name: 'apigee.googleapis.com'
api_version: 'v1'
api_resource_type_kind: 'SharedFlow'
fields:
  - field: 'environment'
  - field: 'org_id'
  - field: 'revision'
  - field: 'service_account'
  - field: 'sharedflow_id'
