resource: 'google_apigee_environment_keyvaluemaps'
generation_type: 'mmv1'
api_service_name: 'apigee.googleapis.com'
api_version: 'v1'
api_resource_type_kind: 'KeyValueMap'
fields:
  - field: 'env_id'
    provider_only: true
  - field: 'name'
