resource: google_scc_folder_notification_config
generation_type: mmv1
source_file: products/securitycenter/FolderNotificationConfig.yaml
api_service_name: securitycenter.googleapis.com
api_version: v1
api_resource_type_kind: NotificationConfig
api_variant_patterns:
    - folders/{folder}/notificationConfigs/{notificationConfig}
fields:
    - field: config_id
      provider_only: true
    - api_field: description
    - field: folder
      provider_only: true
    - api_field: name
    - api_field: pubsubTopic
    - api_field: serviceAccount
    - api_field: streamingConfig.filter
