resource: google_scc_mute_config
generation_type: mmv1
source_file: products/securitycenter/MuteConfig.yaml
api_service_name: securitycenter.googleapis.com
api_version: v1
api_resource_type_kind: MuteConfig
api_variant_patterns:
    - folders/{folder}/muteConfigs/{muteConfig}
    - organizations/{organization}/muteConfigs/{muteConfig}
    - projects/{project}/muteConfigs/{muteConfig}
fields:
    - api_field: createTime
    - api_field: description
    - api_field: expiryTime
    - api_field: filter
    - api_field: mostRecentEditor
    - field: mute_config_id
      provider_only: true
    - api_field: name
    - field: parent
      provider_only: true
    - api_field: type
    - api_field: updateTime
