resource: google_os_config_v2_policy_orchestrator_for_folder
generation_type: mmv1
source_file: products/osconfigv2/PolicyOrchestratorForFolder.yaml
api_service_name: osconfig.googleapis.com
api_version: v2
api_resource_type_kind: PolicyOrchestrator
api_variant_patterns:
    - folders/{folder}/locations/{location}/policyOrchestrators/{policyOrchestrator}
autogen_status: true
fields:
    - api_field: action
    - api_field: createTime
    - api_field: description
    - field: effective_labels
      provider_only: true
    - api_field: etag
    - field: folder_id
      provider_only: true
    - api_field: labels
    - api_field: name
    - api_field: orchestratedResource.id
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.baseline
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.deleted
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.description
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.etag
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.instanceFilter.all
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.instanceFilter.exclusionLabels.labels
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.instanceFilter.inclusionLabels.labels
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.instanceFilter.inventories.osShortName
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.instanceFilter.inventories.osVersion
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.name
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.allowNoResourceGroupMatch
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.description
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.id
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.mode
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.inventoryFilters.osShortName
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.inventoryFilters.osVersion
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.exec.enforce.args
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.exec.enforce.file.allowInsecure
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.exec.enforce.file.gcs.bucket
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.exec.enforce.file.gcs.generation
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.exec.enforce.file.gcs.object
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.exec.enforce.file.localPath
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.exec.enforce.file.remote.sha256Checksum
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.exec.enforce.file.remote.uri
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.exec.enforce.interpreter
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.exec.enforce.outputFilePath
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.exec.enforce.script
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.exec.validate.args
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.exec.validate.file.allowInsecure
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.exec.validate.file.gcs.bucket
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.exec.validate.file.gcs.generation
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.exec.validate.file.gcs.object
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.exec.validate.file.localPath
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.exec.validate.file.remote.sha256Checksum
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.exec.validate.file.remote.uri
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.exec.validate.interpreter
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.exec.validate.outputFilePath
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.exec.validate.script
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.file.content
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.file.file.allowInsecure
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.file.file.gcs.bucket
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.file.file.gcs.generation
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.file.file.gcs.object
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.file.file.localPath
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.file.file.remote.sha256Checksum
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.file.file.remote.uri
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.file.path
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.file.permissions
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.file.state
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.id
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.pkg.apt.name
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.pkg.deb.pullDeps
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.pkg.deb.source.allowInsecure
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.pkg.deb.source.gcs.bucket
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.pkg.deb.source.gcs.generation
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.pkg.deb.source.gcs.object
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.pkg.deb.source.localPath
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.pkg.deb.source.remote.sha256Checksum
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.pkg.deb.source.remote.uri
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.pkg.desiredState
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.pkg.googet.name
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.pkg.msi.properties
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.pkg.msi.source.allowInsecure
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.pkg.msi.source.gcs.bucket
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.pkg.msi.source.gcs.generation
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.pkg.msi.source.gcs.object
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.pkg.msi.source.localPath
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.pkg.msi.source.remote.sha256Checksum
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.pkg.msi.source.remote.uri
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.pkg.rpm.pullDeps
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.pkg.rpm.source.allowInsecure
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.pkg.rpm.source.gcs.bucket
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.pkg.rpm.source.gcs.generation
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.pkg.rpm.source.gcs.object
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.pkg.rpm.source.localPath
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.pkg.rpm.source.remote.sha256Checksum
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.pkg.rpm.source.remote.uri
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.pkg.yum.name
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.pkg.zypper.name
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.repository.apt.archiveType
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.repository.apt.components
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.repository.apt.distribution
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.repository.apt.gpgKey
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.repository.apt.uri
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.repository.goo.name
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.repository.goo.url
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.repository.yum.baseUrl
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.repository.yum.displayName
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.repository.yum.gpgKeys
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.repository.yum.id
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.repository.zypper.baseUrl
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.repository.zypper.displayName
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.repository.zypper.gpgKeys
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.osPolicies.resourceGroups.resources.repository.zypper.id
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.reconciling
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.revisionCreateTime
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.revisionId
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.rollout.disruptionBudget.fixed
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.rollout.disruptionBudget.percent
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.rollout.minWaitDuration
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.rolloutState
    - api_field: orchestratedResource.osPolicyAssignmentV1Payload.uid
    - api_field: orchestrationScope.selectors.locationSelector.includedLocations
    - api_field: orchestrationScope.selectors.resourceHierarchySelector.includedFolders
    - api_field: orchestrationScope.selectors.resourceHierarchySelector.includedProjects
    - api_field: orchestrationState.currentIterationState.error.code
    - api_field: orchestrationState.currentIterationState.error.details.type_url
    - api_field: orchestrationState.currentIterationState.error.details.value
    - api_field: orchestrationState.currentIterationState.error.message
    - api_field: orchestrationState.currentIterationState.failedActions
    - api_field: orchestrationState.currentIterationState.finishTime
    - api_field: orchestrationState.currentIterationState.performedActions
    - api_field: orchestrationState.currentIterationState.progress
    - api_field: orchestrationState.currentIterationState.rolloutResource
    - api_field: orchestrationState.currentIterationState.startTime
    - api_field: orchestrationState.currentIterationState.state
    - api_field: orchestrationState.previousIterationState.error.code
    - api_field: orchestrationState.previousIterationState.error.details.type_url
    - api_field: orchestrationState.previousIterationState.error.details.value
    - api_field: orchestrationState.previousIterationState.error.message
    - api_field: orchestrationState.previousIterationState.failedActions
    - api_field: orchestrationState.previousIterationState.finishTime
    - api_field: orchestrationState.previousIterationState.performedActions
    - api_field: orchestrationState.previousIterationState.progress
    - api_field: orchestrationState.previousIterationState.rolloutResource
    - api_field: orchestrationState.previousIterationState.startTime
    - api_field: orchestrationState.previousIterationState.state
    - field: policy_orchestrator_id
      provider_only: true
    - api_field: reconciling
    - api_field: state
    - field: terraform_labels
      provider_only: true
    - api_field: updateTime
