resource: google_beyondcorp_security_gateway_application
generation_type: mmv1
source_file: products/beyondcorp/SecurityGatewayApplication.yaml
api_service_name: beyondcorp.googleapis.com
api_version: v1
api_resource_type_kind: SecurityGatewayApplication
autogen_status: true
fields:
    - field: application_id
      provider_only: true
    - api_field: createTime
    - api_field: displayName
    - api_field: endpointMatchers.hostname
    - api_field: endpointMatchers.ports
    - api_field: name
    - api_field: schema
    - field: security_gateway_id
      provider_only: true
    - api_field: updateTime
    - api_field: upstreams.egressPolicy.regions
    - api_field: upstreams.external.endpoints.hostname
    - api_field: upstreams.external.endpoints.port
    - api_field: upstreams.network.name
    - api_field: upstreams.proxyProtocol.allowedClientHeaders
    - api_field: upstreams.proxyProtocol.clientIp
    - api_field: upstreams.proxyProtocol.contextualHeaders.deviceInfo.outputType
    - api_field: upstreams.proxyProtocol.contextualHeaders.groupInfo.outputType
    - api_field: upstreams.proxyProtocol.contextualHeaders.outputType
    - api_field: upstreams.proxyProtocol.contextualHeaders.userInfo.outputType
    - api_field: upstreams.proxyProtocol.gatewayIdentity
    - api_field: upstreams.proxyProtocol.metadataHeaders
    - field: deletion_policy
      provider_only: true
