resource: google_vertex_ai_cache_config
generation_type: mmv1
source_file: products/vertexai/CacheConfig.yaml
api_service_name: aiplatform.googleapis.com
api_version: v1
api_resource_type_kind: CacheConfig
fields:
    - api_field: disableCache
    - api_field: name
