resource: google_vertex_ai_endpoint_with_model_garden_deployment
generation_type: mmv1
source_file: products/vertexai/EndpointWithModelGardenDeployment.yaml
api_service_name: aiplatform.googleapis.com
api_version: v1
api_resource_type_kind: Endpoint
autogen_status: true
fields:
    - api_field: deployConfig.dedicatedResources.autoscalingMetricSpecs.metricName
    - api_field: deployConfig.dedicatedResources.autoscalingMetricSpecs.target
    - api_field: deployConfig.dedicatedResources.machineSpec.acceleratorCount
    - api_field: deployConfig.dedicatedResources.machineSpec.acceleratorType
    - api_field: deployConfig.dedicatedResources.machineSpec.machineType
    - api_field: deployConfig.dedicatedResources.machineSpec.multihostGpuNodeCount
    - api_field: deployConfig.dedicatedResources.machineSpec.reservationAffinity.key
    - api_field: deployConfig.dedicatedResources.machineSpec.reservationAffinity.reservationAffinityType
    - api_field: deployConfig.dedicatedResources.machineSpec.reservationAffinity.values
    - api_field: deployConfig.dedicatedResources.machineSpec.tpuTopology
    - api_field: deployConfig.dedicatedResources.maxReplicaCount
    - api_field: deployConfig.dedicatedResources.minReplicaCount
    - api_field: deployConfig.dedicatedResources.requiredReplicaCount
    - api_field: deployConfig.dedicatedResources.spot
    - api_field: deployConfig.fastTryoutEnabled
    - api_field: deployConfig.systemLabels
    - api_field: deployedModelDisplayName
    - api_field: deployedModelId
    - field: endpoint
      provider_only: true
    - api_field: endpointConfig.dedicatedEndpointEnabled
    - api_field: endpointConfig.endpointDisplayName
    - api_field: endpointConfig.privateServiceConnectConfig.enablePrivateServiceConnect
    - api_field: endpointConfig.privateServiceConnectConfig.projectAllowlist
    - api_field: endpointConfig.privateServiceConnectConfig.pscAutomationConfigs.errorMessage
    - api_field: endpointConfig.privateServiceConnectConfig.pscAutomationConfigs.forwardingRule
    - api_field: endpointConfig.privateServiceConnectConfig.pscAutomationConfigs.ipAddress
    - api_field: endpointConfig.privateServiceConnectConfig.pscAutomationConfigs.network
    - api_field: endpointConfig.privateServiceConnectConfig.pscAutomationConfigs.projectId
    - api_field: endpointConfig.privateServiceConnectConfig.pscAutomationConfigs.state
    - api_field: endpointConfig.privateServiceConnectConfig.serviceAttachment
    - api_field: huggingFaceModelId
    - field: location
      provider_only: true
    - api_field: modelConfig.acceptEula
    - api_field: modelConfig.containerSpec.args
    - api_field: modelConfig.containerSpec.command
    - api_field: modelConfig.containerSpec.deploymentTimeout
    - api_field: modelConfig.containerSpec.env.name
    - api_field: modelConfig.containerSpec.env.value
    - api_field: modelConfig.containerSpec.grpcPorts.containerPort
    - api_field: modelConfig.containerSpec.healthProbe.exec.command
    - api_field: modelConfig.containerSpec.healthProbe.failureThreshold
    - api_field: modelConfig.containerSpec.healthProbe.grpc.port
    - api_field: modelConfig.containerSpec.healthProbe.grpc.service
    - api_field: modelConfig.containerSpec.healthProbe.httpGet.host
    - api_field: modelConfig.containerSpec.healthProbe.httpGet.httpHeaders.name
    - api_field: modelConfig.containerSpec.healthProbe.httpGet.httpHeaders.value
    - api_field: modelConfig.containerSpec.healthProbe.httpGet.path
    - api_field: modelConfig.containerSpec.healthProbe.httpGet.port
    - api_field: modelConfig.containerSpec.healthProbe.httpGet.scheme
    - api_field: modelConfig.containerSpec.healthProbe.initialDelaySeconds
    - api_field: modelConfig.containerSpec.healthProbe.periodSeconds
    - api_field: modelConfig.containerSpec.healthProbe.successThreshold
    - api_field: modelConfig.containerSpec.healthProbe.tcpSocket.host
    - api_field: modelConfig.containerSpec.healthProbe.tcpSocket.port
    - api_field: modelConfig.containerSpec.healthProbe.timeoutSeconds
    - api_field: modelConfig.containerSpec.healthRoute
    - api_field: modelConfig.containerSpec.imageUri
    - api_field: modelConfig.containerSpec.livenessProbe.exec.command
    - api_field: modelConfig.containerSpec.livenessProbe.failureThreshold
    - api_field: modelConfig.containerSpec.livenessProbe.grpc.port
    - api_field: modelConfig.containerSpec.livenessProbe.grpc.service
    - api_field: modelConfig.containerSpec.livenessProbe.httpGet.host
    - api_field: modelConfig.containerSpec.livenessProbe.httpGet.httpHeaders.name
    - api_field: modelConfig.containerSpec.livenessProbe.httpGet.httpHeaders.value
    - api_field: modelConfig.containerSpec.livenessProbe.httpGet.path
    - api_field: modelConfig.containerSpec.livenessProbe.httpGet.port
    - api_field: modelConfig.containerSpec.livenessProbe.httpGet.scheme
    - api_field: modelConfig.containerSpec.livenessProbe.initialDelaySeconds
    - api_field: modelConfig.containerSpec.livenessProbe.periodSeconds
    - api_field: modelConfig.containerSpec.livenessProbe.successThreshold
    - api_field: modelConfig.containerSpec.livenessProbe.tcpSocket.host
    - api_field: modelConfig.containerSpec.livenessProbe.tcpSocket.port
    - api_field: modelConfig.containerSpec.livenessProbe.timeoutSeconds
    - api_field: modelConfig.containerSpec.ports.containerPort
    - api_field: modelConfig.containerSpec.predictRoute
    - api_field: modelConfig.containerSpec.sharedMemorySizeMb
    - api_field: modelConfig.containerSpec.startupProbe.exec.command
    - api_field: modelConfig.containerSpec.startupProbe.failureThreshold
    - api_field: modelConfig.containerSpec.startupProbe.grpc.port
    - api_field: modelConfig.containerSpec.startupProbe.grpc.service
    - api_field: modelConfig.containerSpec.startupProbe.httpGet.host
    - api_field: modelConfig.containerSpec.startupProbe.httpGet.httpHeaders.name
    - api_field: modelConfig.containerSpec.startupProbe.httpGet.httpHeaders.value
    - api_field: modelConfig.containerSpec.startupProbe.httpGet.path
    - api_field: modelConfig.containerSpec.startupProbe.httpGet.port
    - api_field: modelConfig.containerSpec.startupProbe.httpGet.scheme
    - api_field: modelConfig.containerSpec.startupProbe.initialDelaySeconds
    - api_field: modelConfig.containerSpec.startupProbe.periodSeconds
    - api_field: modelConfig.containerSpec.startupProbe.successThreshold
    - api_field: modelConfig.containerSpec.startupProbe.tcpSocket.host
    - api_field: modelConfig.containerSpec.startupProbe.tcpSocket.port
    - api_field: modelConfig.containerSpec.startupProbe.timeoutSeconds
    - api_field: modelConfig.huggingFaceAccessToken
    - api_field: modelConfig.huggingFaceCacheEnabled
    - api_field: modelConfig.modelDisplayName
    - api_field: publisherModelName
