resource: 'google_vertex_ai_deployment_resource_pool'
generation_type: 'mmv1'
source_file: 'products/vertexai/DeploymentResourcePool.yaml'
api_service_name: 'aiplatform.googleapis.com'
api_version: 'v1'
api_resource_type_kind: 'DeploymentResourcePool'
fields:
  - field: 'create_time'
  - field: 'dedicated_resources.autoscaling_metric_specs.metric_name'
  - field: 'dedicated_resources.autoscaling_metric_specs.target'
  - field: 'dedicated_resources.machine_spec.accelerator_count'
  - field: 'dedicated_resources.machine_spec.accelerator_type'
  - field: 'dedicated_resources.machine_spec.machine_type'
  - field: 'dedicated_resources.max_replica_count'
  - field: 'dedicated_resources.min_replica_count'
  - field: 'name'
  - field: 'region'
    provider_only: true
