resource: google_backup_dr_service_config
generation_type: mmv1
source_file: products/backupdr/ServiceConfig.yaml
api_service_name: backupdr.googleapis.com
api_version: v1
api_resource_type_kind: ServiceConfig
fields:
    - field: location
      provider_only: true
    - api_field: resourceType
