resource: 'google_cloud_security_compliance_framework_deployment'
generation_type: 'mmv1'
source_file: 'products/cloudsecuritycompliance/FrameworkDeployment.yaml'
api_service_name: 'cloudsecuritycompliance.googleapis.com'
api_version: 'v1'
api_resource_type_kind: 'FrameworkDeployment'
autogen_status: true
fields:
  - api_field: 'cloudControlDeploymentReferences.cloudControlDeployment'
  - api_field: 'cloudControlMetadata.cloudControlDetails.majorRevisionId'
  - api_field: 'cloudControlMetadata.cloudControlDetails.name'
  - api_field: 'cloudControlMetadata.cloudControlDetails.parameters.name'
  - api_field: 'cloudControlMetadata.cloudControlDetails.parameters.parameterValue.boolValue'
  - api_field: 'cloudControlMetadata.cloudControlDetails.parameters.parameterValue.numberValue'
  - api_field: 'cloudControlMetadata.cloudControlDetails.parameters.parameterValue.stringListValue.values'
  - api_field: 'cloudControlMetadata.cloudControlDetails.parameters.parameterValue.stringValue'
  - api_field: 'cloudControlMetadata.enforcementMode'
  - api_field: 'computedTargetResource'
  - api_field: 'createTime'
  - api_field: 'deploymentState'
  - api_field: 'description'
  - api_field: 'etag'
  - api_field: 'framework.framework'
  - api_field: 'framework.majorRevisionId'
  - field: 'framework_deployment_id'
    provider_only: true
  - field: 'location'
    provider_only: true
  - api_field: 'name'
  - field: 'organization'
    provider_only: true
  - api_field: 'targetResourceConfig.existingTargetResource'
  - api_field: 'targetResourceConfig.targetResourceCreationConfig.folderCreationConfig.folderDisplayName'
  - api_field: 'targetResourceConfig.targetResourceCreationConfig.folderCreationConfig.parent'
  - api_field: 'targetResourceConfig.targetResourceCreationConfig.projectCreationConfig.billingAccountId'
  - api_field: 'targetResourceConfig.targetResourceCreationConfig.projectCreationConfig.parent'
  - api_field: 'targetResourceConfig.targetResourceCreationConfig.projectCreationConfig.projectDisplayName'
  - api_field: 'targetResourceDisplayName'
  - api_field: 'updateTime'
