resource: 'google_monitoring_uptime_check_config'
generation_type: 'mmv1'
source_file: 'products/monitoring/UptimeCheckConfig.yaml'
api_service_name: 'monitoring.googleapis.com'
api_version: 'v3'
api_resource_type_kind: 'UptimeCheckConfig'
fields:
  - field: 'checker_type'
  - field: 'content_matchers.content'
  - field: 'content_matchers.json_path_matcher.json_matcher'
  - field: 'content_matchers.json_path_matcher.json_path'
  - field: 'content_matchers.matcher'
  - field: 'display_name'
  - field: 'http_check.accepted_response_status_codes.status_class'
  - field: 'http_check.accepted_response_status_codes.status_value'
  - field: 'http_check.auth_info.password'
  - field: 'http_check.auth_info.password_wo'
  - field: 'http_check.auth_info.password_wo_version'
  - field: 'http_check.auth_info.username'
  - field: 'http_check.body'
  - field: 'http_check.content_type'
  - field: 'http_check.custom_content_type'
  - field: 'http_check.headers'
  - field: 'http_check.mask_headers'
  - field: 'http_check.path'
  - field: 'http_check.ping_config.pings_count'
  - field: 'http_check.port'
  - field: 'http_check.request_method'
  - field: 'http_check.service_agent_authentication.type'
  - field: 'http_check.use_ssl'
  - field: 'http_check.validate_ssl'
  - field: 'log_check_failures'
  - field: 'monitored_resource.labels'
  - field: 'monitored_resource.type'
  - field: 'name'
  - field: 'period'
  - field: 'resource_group.group_id'
  - field: 'resource_group.resource_type'
  - field: 'selected_regions'
  - field: 'synthetic_monitor.cloud_function_v2.name'
  - field: 'tcp_check.ping_config.pings_count'
  - field: 'tcp_check.port'
  - field: 'timeout'
  - field: 'uptime_check_id'
    api_field: 'id'
  - field: 'user_labels'
