resource: 'google_app_engine_application'
generation_type: 'handwritten'
api_service_name: 'appengine.googleapis.com'
api_version: 'v1'
api_resource_type_kind: 'Application'
cai_asset_name_format: '//appengine.googleapis.com/{{name}}'
fields:
  - field: 'app_id'
  - api_field: 'authDomain'
  - api_field: 'codeBucket'
  - api_field: 'databaseType'
  - api_field: 'defaultBucket'
  - api_field: 'defaultHostname'
  - api_field: 'featureSettings.splitHealthChecks'
  - api_field: 'gcrDomain'
  - api_field: 'iap.enabled'
  - api_field: 'iap.oauth2ClientId'
  - api_field: 'iap.oauth2ClientSecret'
  - api_field: 'iap.oauth2ClientSecretSha256'
  - api_field: 'locationId'
  - api_field: 'name'
  - field: 'project'
  - api_field: 'servingStatus'
  - api_field: 'ssl_policy'
  - field: 'url_dispatch_rule.domain'
  - field: 'url_dispatch_rule.path'
  - field: 'url_dispatch_rule.service'
