resource: 'google_app_engine_service_network_settings'
generation_type: 'mmv1'
api_service_name: 'appengine.googleapis.com'
api_version: 'v1'
api_resource_type_kind: 'Service'
fields:
  - field: 'network_settings.ingress_traffic_allowed'
  - field: 'service'
    api_field: 'id'
