resource: 'google_app_engine_application_url_dispatch_rules'
generation_type: 'mmv1'
source_file: 'products/appengine/ApplicationUrlDispatchRules.yaml'
api_service_name: 'appengine.googleapis.com'
api_version: 'v1'
api_resource_type_kind: 'Application'
fields:
  - field: 'dispatch_rules.domain'
  - field: 'dispatch_rules.path'
  - field: 'dispatch_rules.service'
