resource: 'google_storage_insights_report_config'
generation_type: 'mmv1'
source_file: 'products/storageinsights/ReportConfig.yaml'
api_service_name: 'storageinsights.googleapis.com'
api_version: 'v1'
api_resource_type_kind: 'ReportConfig'
fields:
  - field: 'csv_options.delimiter'
  - field: 'csv_options.header_required'
  - field: 'csv_options.record_separator'
  - field: 'display_name'
  - field: 'force_destroy'
    provider_only: true
  - field: 'frequency_options.end_date.day'
  - field: 'frequency_options.end_date.month'
  - field: 'frequency_options.end_date.year'
  - field: 'frequency_options.frequency'
  - field: 'frequency_options.start_date.day'
  - field: 'frequency_options.start_date.month'
  - field: 'frequency_options.start_date.year'
  - field: 'location'
    provider_only: true
  - field: 'name'
  - field: 'object_metadata_report_options.metadata_fields'
  - field: 'object_metadata_report_options.storage_destination_options.bucket'
  - field: 'object_metadata_report_options.storage_destination_options.destination_path'
  - field: 'object_metadata_report_options.storage_filters.bucket'
  - field: 'parquet_options'
