resource: google_storage_insights_dataset_config
generation_type: mmv1
source_file: products/storageinsights/DatasetConfig.yaml
api_service_name: storageinsights.googleapis.com
api_version: v1
api_resource_type_kind: DatasetConfig
fields:
    - api_field: createTime
    - field: dataset_config_id
      provider_only: true
    - api_field: datasetConfigState
    - api_field: description
    - api_field: excludeCloudStorageBuckets.cloudStorageBuckets.bucketName
    - api_field: excludeCloudStorageBuckets.cloudStorageBuckets.bucketPrefixRegex
    - api_field: excludeCloudStorageLocations.locations
    - api_field: identity.name
    - api_field: identity.type
    - api_field: includeCloudStorageBuckets.cloudStorageBuckets.bucketName
    - api_field: includeCloudStorageBuckets.cloudStorageBuckets.bucketPrefixRegex
    - api_field: includeCloudStorageLocations.locations
    - api_field: includeNewlyCreatedBuckets
    - api_field: link.dataset
    - api_field: link.linked
    - field: link_dataset
      provider_only: true
    - field: location
      provider_only: true
    - api_field: name
    - api_field: organizationNumber
    - api_field: organizationScope
    - api_field: retentionPeriodDays
    - api_field: sourceFolders.folderNumbers
    - api_field: sourceProjects.projectNumbers
    - api_field: uid
    - api_field: updateTime
