resource: 'google_data_loss_prevention_discovery_config'
generation_type: 'mmv1'
source_file: 'products/dlp/DiscoveryConfig.yaml'
api_service_name: 'dlp.googleapis.com'
api_version: 'v2'
api_resource_type_kind: 'DiscoveryConfig'
fields:
  - field: 'actions.export_data.profile_table.dataset_id'
  - field: 'actions.export_data.profile_table.project_id'
  - field: 'actions.export_data.profile_table.table_id'
  - field: 'actions.pub_sub_notification.detail_of_message'
  - field: 'actions.pub_sub_notification.event'
  - field: 'actions.pub_sub_notification.pubsub_condition.expressions.conditions.minimum_risk_score'
  - field: 'actions.pub_sub_notification.pubsub_condition.expressions.conditions.minimum_sensitivity_score'
  - field: 'actions.pub_sub_notification.pubsub_condition.expressions.logical_operator'
  - field: 'actions.pub_sub_notification.topic'
  - field: 'actions.publish_to_dataplex_catalog'
  - field: 'actions.tag_resources.lower_data_risk_to_low'
  - field: 'actions.tag_resources.profile_generations_to_tag'
  - field: 'actions.tag_resources.tag_conditions.sensitivity_score.score'
  - field: 'actions.tag_resources.tag_conditions.tag.namespaced_value'
  - field: 'create_time'
  - field: 'display_name'
  - field: 'errors.details.code'
  - field: 'errors.details.details'
  - field: 'errors.details.message'
  - field: 'errors.timestamp'
  - field: 'inspect_templates'
  - field: 'last_run_time'
  - field: 'location'
    provider_only: true
  - field: 'name'
  - field: 'org_config.location.folder_id'
  - field: 'org_config.location.organization_id'
  - field: 'org_config.project_id'
  - field: 'other_cloud_starting_location.aws_location.account_id'
  - field: 'other_cloud_starting_location.aws_location.all_asset_inventory_assets'
  - field: 'parent'
    provider_only: true
  - field: 'status'
  - field: 'targets.big_query_target.cadence.inspect_template_modified_cadence.frequency'
  - field: 'targets.big_query_target.cadence.schema_modified_cadence.frequency'
  - field: 'targets.big_query_target.cadence.schema_modified_cadence.types'
  - field: 'targets.big_query_target.cadence.table_modified_cadence.frequency'
  - field: 'targets.big_query_target.cadence.table_modified_cadence.types'
  - field: 'targets.big_query_target.conditions.created_after'
  - field: 'targets.big_query_target.conditions.or_conditions.min_age'
  - field: 'targets.big_query_target.conditions.or_conditions.min_row_count'
  - field: 'targets.big_query_target.conditions.type_collection'
  - field: 'targets.big_query_target.conditions.types.types'
  - field: 'targets.big_query_target.disabled'
  - field: 'targets.big_query_target.filter.other_tables'
  - field: 'targets.big_query_target.filter.table_reference.dataset_id'
  - field: 'targets.big_query_target.filter.table_reference.table_id'
  - field: 'targets.big_query_target.filter.tables.include_regexes.patterns.dataset_id_regex'
  - field: 'targets.big_query_target.filter.tables.include_regexes.patterns.project_id_regex'
  - field: 'targets.big_query_target.filter.tables.include_regexes.patterns.table_id_regex'
  - field: 'targets.cloud_sql_target.conditions.database_engines'
  - field: 'targets.cloud_sql_target.conditions.types'
  - field: 'targets.cloud_sql_target.disabled'
  - field: 'targets.cloud_sql_target.filter.collection.include_regexes.patterns.database_regex'
  - field: 'targets.cloud_sql_target.filter.collection.include_regexes.patterns.database_resource_name_regex'
  - field: 'targets.cloud_sql_target.filter.collection.include_regexes.patterns.instance_regex'
  - field: 'targets.cloud_sql_target.filter.collection.include_regexes.patterns.project_id_regex'
  - field: 'targets.cloud_sql_target.filter.database_resource_reference.database'
  - field: 'targets.cloud_sql_target.filter.database_resource_reference.database_resource'
  - field: 'targets.cloud_sql_target.filter.database_resource_reference.instance'
  - field: 'targets.cloud_sql_target.filter.database_resource_reference.project_id'
  - field: 'targets.cloud_sql_target.filter.others'
  - field: 'targets.cloud_sql_target.generation_cadence.inspect_template_modified_cadence.frequency'
  - field: 'targets.cloud_sql_target.generation_cadence.refresh_frequency'
  - field: 'targets.cloud_sql_target.generation_cadence.schema_modified_cadence.frequency'
  - field: 'targets.cloud_sql_target.generation_cadence.schema_modified_cadence.types'
  - field: 'targets.cloud_storage_target.conditions.cloud_storage_conditions.included_bucket_attributes'
  - field: 'targets.cloud_storage_target.conditions.cloud_storage_conditions.included_object_attributes'
  - field: 'targets.cloud_storage_target.conditions.created_after'
  - field: 'targets.cloud_storage_target.conditions.min_age'
  - field: 'targets.cloud_storage_target.disabled'
  - field: 'targets.cloud_storage_target.filter.cloud_storage_resource_reference.bucket_name'
  - field: 'targets.cloud_storage_target.filter.cloud_storage_resource_reference.project_id'
  - field: 'targets.cloud_storage_target.filter.collection.include_regexes.patterns.cloud_storage_regex.bucket_name_regex'
  - field: 'targets.cloud_storage_target.filter.collection.include_regexes.patterns.cloud_storage_regex.project_id_regex'
  - field: 'targets.cloud_storage_target.filter.others'
  - field: 'targets.cloud_storage_target.generation_cadence.inspect_template_modified_cadence.frequency'
  - field: 'targets.cloud_storage_target.generation_cadence.refresh_frequency'
  - field: 'targets.other_cloud_target.conditions.amazon_s3_bucket_conditions.bucket_types'
  - field: 'targets.other_cloud_target.conditions.amazon_s3_bucket_conditions.object_storage_classes'
  - field: 'targets.other_cloud_target.conditions.min_age'
  - field: 'targets.other_cloud_target.data_source_type.data_source'
  - field: 'targets.other_cloud_target.disabled'
  - field: 'targets.other_cloud_target.filter.collection.include_regexes.patterns.amazon_s3_bucket_regex.aws_account_regex.account_id_regex'
  - field: 'targets.other_cloud_target.filter.collection.include_regexes.patterns.amazon_s3_bucket_regex.bucket_name_regex'
  - field: 'targets.other_cloud_target.filter.others'
  - field: 'targets.other_cloud_target.filter.single_resource.amazon_s3_bucket.aws_account.account_id'
  - field: 'targets.other_cloud_target.filter.single_resource.amazon_s3_bucket.bucket_name'
  - field: 'targets.other_cloud_target.generation_cadence.inspect_template_modified_cadence.frequency'
  - field: 'targets.other_cloud_target.generation_cadence.refresh_frequency'
  - field: 'targets.secrets_target'
  - field: 'update_time'
