resource: google_data_loss_prevention_discovery_config
generation_type: mmv1
source_file: products/dlp/DiscoveryConfig.yaml
api_service_name: dlp.googleapis.com
api_version: v2
api_resource_type_kind: DiscoveryConfig
fields:
    - api_field: actions.exportData.profileTable.datasetId
    - api_field: actions.exportData.profileTable.projectId
    - api_field: actions.exportData.profileTable.tableId
    - api_field: actions.exportData.sampleFindingsTable.datasetId
    - api_field: actions.exportData.sampleFindingsTable.projectId
    - api_field: actions.exportData.sampleFindingsTable.tableId
    - api_field: actions.pubSubNotification.detailOfMessage
    - api_field: actions.pubSubNotification.event
    - api_field: actions.pubSubNotification.pubsubCondition.expressions.conditions.minimumRiskScore
    - api_field: actions.pubSubNotification.pubsubCondition.expressions.conditions.minimumSensitivityScore
    - api_field: actions.pubSubNotification.pubsubCondition.expressions.logicalOperator
    - api_field: actions.pubSubNotification.topic
    - api_field: actions.publishToChronicle
    - api_field: actions.publishToDataplexCatalog
    - api_field: actions.publishToScc
    - api_field: actions.tagResources.lowerDataRiskToLow
    - api_field: actions.tagResources.profileGenerationsToTag
    - api_field: actions.tagResources.tagConditions.sensitivityScore.score
    - api_field: actions.tagResources.tagConditions.tag.namespacedValue
    - api_field: createTime
    - api_field: displayName
    - api_field: errors.details.code
    - api_field: errors.details.details
    - api_field: errors.details.message
    - api_field: errors.timestamp
    - api_field: inspectTemplates
    - api_field: lastRunTime
    - field: location
      provider_only: true
    - api_field: name
    - api_field: orgConfig.location.folderId
    - api_field: orgConfig.location.organizationId
    - api_field: orgConfig.projectId
    - api_field: otherCloudStartingLocation.awsLocation.accountId
    - api_field: otherCloudStartingLocation.awsLocation.allAssetInventoryAssets
    - field: parent
      provider_only: true
    - api_field: status
    - api_field: targets.bigQueryTarget.cadence.inspectTemplateModifiedCadence.frequency
    - api_field: targets.bigQueryTarget.cadence.schemaModifiedCadence.frequency
    - api_field: targets.bigQueryTarget.cadence.schemaModifiedCadence.types
    - api_field: targets.bigQueryTarget.cadence.tableModifiedCadence.frequency
    - api_field: targets.bigQueryTarget.cadence.tableModifiedCadence.types
    - api_field: targets.bigQueryTarget.conditions.createdAfter
    - api_field: targets.bigQueryTarget.conditions.orConditions.minAge
    - api_field: targets.bigQueryTarget.conditions.orConditions.minRowCount
    - api_field: targets.bigQueryTarget.conditions.typeCollection
    - api_field: targets.bigQueryTarget.conditions.types.types
    - api_field: targets.bigQueryTarget.disabled
    - api_field: targets.bigQueryTarget.filter.otherTables
    - api_field: targets.bigQueryTarget.filter.tableReference.datasetId
    - api_field: targets.bigQueryTarget.filter.tableReference.projectId
    - api_field: targets.bigQueryTarget.filter.tableReference.tableId
    - api_field: targets.bigQueryTarget.filter.tables.includeRegexes.patterns.datasetIdRegex
    - api_field: targets.bigQueryTarget.filter.tables.includeRegexes.patterns.projectIdRegex
    - api_field: targets.bigQueryTarget.filter.tables.includeRegexes.patterns.tableIdRegex
    - api_field: targets.cloudSqlTarget.conditions.databaseEngines
    - api_field: targets.cloudSqlTarget.conditions.types
    - api_field: targets.cloudSqlTarget.disabled
    - api_field: targets.cloudSqlTarget.filter.collection.includeRegexes.patterns.databaseRegex
    - api_field: targets.cloudSqlTarget.filter.collection.includeRegexes.patterns.databaseResourceNameRegex
    - api_field: targets.cloudSqlTarget.filter.collection.includeRegexes.patterns.instanceRegex
    - api_field: targets.cloudSqlTarget.filter.collection.includeRegexes.patterns.projectIdRegex
    - api_field: targets.cloudSqlTarget.filter.databaseResourceReference.database
    - api_field: targets.cloudSqlTarget.filter.databaseResourceReference.databaseResource
    - api_field: targets.cloudSqlTarget.filter.databaseResourceReference.instance
    - api_field: targets.cloudSqlTarget.filter.databaseResourceReference.projectId
    - api_field: targets.cloudSqlTarget.filter.others
    - api_field: targets.cloudSqlTarget.generationCadence.inspectTemplateModifiedCadence.frequency
    - api_field: targets.cloudSqlTarget.generationCadence.refreshFrequency
    - api_field: targets.cloudSqlTarget.generationCadence.schemaModifiedCadence.frequency
    - api_field: targets.cloudSqlTarget.generationCadence.schemaModifiedCadence.types
    - api_field: targets.cloudStorageTarget.conditions.cloudStorageConditions.includedBucketAttributes
    - api_field: targets.cloudStorageTarget.conditions.cloudStorageConditions.includedObjectAttributes
    - api_field: targets.cloudStorageTarget.conditions.createdAfter
    - api_field: targets.cloudStorageTarget.conditions.minAge
    - api_field: targets.cloudStorageTarget.disabled
    - api_field: targets.cloudStorageTarget.filter.cloudStorageResourceReference.bucketName
    - api_field: targets.cloudStorageTarget.filter.cloudStorageResourceReference.projectId
    - api_field: targets.cloudStorageTarget.filter.collection.includeRegexes.patterns.cloudStorageRegex.bucketNameRegex
    - api_field: targets.cloudStorageTarget.filter.collection.includeRegexes.patterns.cloudStorageRegex.projectIdRegex
    - api_field: targets.cloudStorageTarget.filter.collection.includeTags.tagFilters.namespacedTagKey
    - api_field: targets.cloudStorageTarget.filter.collection.includeTags.tagFilters.namespacedTagValue
    - api_field: targets.cloudStorageTarget.filter.others
    - api_field: targets.cloudStorageTarget.generationCadence.inspectTemplateModifiedCadence.frequency
    - api_field: targets.cloudStorageTarget.generationCadence.refreshFrequency
    - api_field: targets.otherCloudTarget.conditions.amazonS3BucketConditions.bucketTypes
    - api_field: targets.otherCloudTarget.conditions.amazonS3BucketConditions.objectStorageClasses
    - api_field: targets.otherCloudTarget.conditions.minAge
    - api_field: targets.otherCloudTarget.dataSourceType.dataSource
    - api_field: targets.otherCloudTarget.disabled
    - api_field: targets.otherCloudTarget.filter.collection.includeRegexes.patterns.amazonS3BucketRegex.awsAccountRegex.accountIdRegex
    - api_field: targets.otherCloudTarget.filter.collection.includeRegexes.patterns.amazonS3BucketRegex.bucketNameRegex
    - api_field: targets.otherCloudTarget.filter.others
    - api_field: targets.otherCloudTarget.filter.singleResource.amazonS3Bucket.awsAccount.accountId
    - api_field: targets.otherCloudTarget.filter.singleResource.amazonS3Bucket.bucketName
    - api_field: targets.otherCloudTarget.generationCadence.inspectTemplateModifiedCadence.frequency
    - api_field: targets.otherCloudTarget.generationCadence.refreshFrequency
    - api_field: targets.secretsTarget
    - api_field: updateTime
