resource: google_storage_control_folder_intelligence_config
generation_type: mmv1
source_file: products/storagecontrol/FolderIntelligenceConfig.yaml
api_service_name: storage.googleapis.com
api_version: v2
api_resource_type_kind: IntelligenceConfig
api_variant_patterns:
    - folders/{folder}/locations/{location}/intelligenceConfig
fields:
    - api_field: editionConfig
    - api_field: effectiveIntelligenceConfig.effectiveEdition
    - api_field: effectiveIntelligenceConfig.intelligenceConfig
    - api_field: filter.excludedCloudStorageBuckets.bucketIdRegexes
    - api_field: filter.excludedCloudStorageLocations.locations
    - api_field: filter.includedCloudStorageBuckets.bucketIdRegexes
    - api_field: filter.includedCloudStorageLocations.locations
    - api_field: name
    - api_field: trialConfig.expireTime
    - api_field: updateTime
