resource: google_network_security_intercept_deployment
generation_type: mmv1
source_file: products/networksecurity/InterceptDeployment.yaml
api_service_name: networksecurity.googleapis.com
api_version: v1
api_resource_type_kind: InterceptDeployment
fields:
    - api_field: createTime
    - api_field: description
    - field: effective_labels
      provider_only: true
    - api_field: forwardingRule
    - api_field: interceptDeploymentGroup
    - field: intercept_deployment_id
      provider_only: true
    - api_field: labels
    - field: location
      provider_only: true
    - api_field: name
    - api_field: reconciling
    - api_field: state
    - field: terraform_labels
      provider_only: true
    - api_field: updateTime
