resource: google_network_security_mirroring_deployment_group
generation_type: mmv1
source_file: products/networksecurity/MirroringDeploymentGroup.yaml
api_service_name: networksecurity.googleapis.com
api_version: v1
api_resource_type_kind: MirroringDeploymentGroup
fields:
    - api_field: connectedEndpointGroups.name
    - api_field: createTime
    - api_field: description
    - field: effective_labels
      provider_only: true
    - api_field: labels
    - field: location
      provider_only: true
    - api_field: locations.location
    - api_field: locations.state
    - field: mirroring_deployment_group_id
      provider_only: true
    - api_field: name
    - api_field: network
    - api_field: reconciling
    - api_field: state
    - field: terraform_labels
      provider_only: true
    - api_field: updateTime
