resource: 'google_compute_network_peering_routes_config'
generation_type: 'mmv1'
source_file: 'products/compute/NetworkPeeringRoutesConfig.yaml'
api_service_name: 'compute.googleapis.com'
api_version: 'v1'
api_resource_type_kind: 'Network'
fields:
  - field: 'export_custom_routes'
  - field: 'export_subnet_routes_with_public_ip'
  - field: 'import_custom_routes'
  - field: 'import_subnet_routes_with_public_ip'
  - field: 'network'
    provider_only: true
  - field: 'peering'
    api_field: 'name'
