resource: 'google_compute_instance_settings'
generation_type: 'mmv1'
source_file: 'products/compute/InstanceSettings.yaml'
api_service_name: 'compute.googleapis.com'
api_version: 'v1'
api_resource_type_kind: 'InstanceSettings'
fields:
  - field: 'fingerprint'
  - field: 'metadata.items'
  - field: 'zone'
