# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

resource: 'google_identity_platform_oauth_idp_config'
generation_type: 'mmv1'
source_file: 'products/identityplatform/OauthIdpConfig.yaml'
api_service_name: 'identitytoolkit.googleapis.com'
api_version: 'v2'
api_resource_type_kind: 'OAuthIdpConfig'
fields:
  - field: 'client_id'
  - field: 'client_secret'
  - field: 'display_name'
  - field: 'enabled'
  - field: 'issuer'
  - field: 'name'
  - field: 'response_type.code'
  - field: 'response_type.id_token'
