resource: google_identity_platform_inbound_saml_config
generation_type: mmv1
source_file: products/identityplatform/InboundSamlConfig.yaml
api_service_name: identitytoolkit.googleapis.com
api_version: v2
api_resource_type_kind: InboundSamlConfig
fields:
    - api_field: displayName
    - api_field: enabled
    - api_field: idpConfig.idpCertificates.x509Certificate
    - api_field: idpConfig.idpEntityId
    - api_field: idpConfig.signRequest
    - api_field: idpConfig.ssoUrl
    - api_field: name
    - api_field: spConfig.callbackUri
    - api_field: spConfig.spCertificates.x509Certificate
    - api_field: spConfig.spEntityId
    - field: deletion_policy
      provider_only: true
