resource: google_identity_platform_tenant_oauth_idp_config
generation_type: mmv1
source_file: products/identityplatform/TenantOauthIdpConfig.yaml
api_service_name: identitytoolkit.googleapis.com
api_version: v2
api_resource_type_kind: OAuthIdpConfig
fields:
    - api_field: clientId
    - api_field: clientSecret
    - api_field: displayName
    - api_field: enabled
    - api_field: issuer
    - api_field: name
    - field: tenant
      provider_only: true
    - field: deletion_policy
      provider_only: true
