resource: 'google_composer_user_workloads_config_map'
generation_type: 'mmv1'
source_file: 'products/composer/UserWorkloadsConfigMap.yaml'
api_service_name: 'composer.googleapis.com'
api_version: 'v1'
api_resource_type_kind: 'UserWorkloadsConfigMap'
fields:
  - field: 'data'
  - field: 'environment'
    provider_only: true
  - field: 'name'
  - field: 'region'
    provider_only: true
