resource: 'google_composer_environment'
generation_type: 'handwritten'
api_service_name: 'composer.googleapis.com'
api_version: 'v1'
api_resource_type_kind: 'Environment'
fields:
  - field: 'config.airflow_uri'
  - field: 'config.dag_gcs_prefix'
  - field: 'config.data_retention_config.airflow_metadata_retention_config.retention_days'
  - field: 'config.data_retention_config.airflow_metadata_retention_config.retention_mode'
  - field: 'config.data_retention_config.task_logs_retention_config.storage_mode'
  - field: 'config.database_config.machine_type'
  - field: 'config.database_config.zone'
  - field: 'config.enable_private_builds_only'
  - field: 'config.enable_private_environment'
  - field: 'config.encryption_config.kms_key_name'
  - field: 'config.environment_size'
  - field: 'config.gke_cluster'
  - field: 'config.maintenance_window.end_time'
  - field: 'config.maintenance_window.recurrence'
  - field: 'config.maintenance_window.start_time'
  - field: 'config.master_authorized_networks_config.cidr_blocks.cidr_block'
  - field: 'config.master_authorized_networks_config.cidr_blocks.display_name'
  - field: 'config.master_authorized_networks_config.enabled'
  - field: 'config.node_config.composer_internal_ipv4_cidr_block'
  - field: 'config.node_config.composer_network_attachment'
  - field: 'config.node_config.disk_size_gb'
  - field: 'config.node_config.enable_ip_masq_agent'
  - field: 'config.node_config.ip_allocation_policy.cluster_ipv4_cidr_block'
  - field: 'config.node_config.ip_allocation_policy.cluster_secondary_range_name'
  - field: 'config.node_config.ip_allocation_policy.services_ipv4_cidr_block'
  - field: 'config.node_config.ip_allocation_policy.services_secondary_range_name'
  - field: 'config.node_config.ip_allocation_policy.use_ip_aliases'
  - field: 'config.node_config.machine_type'
  - field: 'config.node_config.network'
  - field: 'config.node_config.oauth_scopes'
  - field: 'config.node_config.service_account'
  - field: 'config.node_config.subnetwork'
  - field: 'config.node_config.tags'
  - field: 'config.node_config.zone'
  - field: 'config.node_count'
  - field: 'config.private_environment_config.cloud_composer_connection_subnetwork'
  - field: 'config.private_environment_config.cloud_composer_network_ipv4_cidr_block'
  - field: 'config.private_environment_config.cloud_sql_ipv4_cidr_block'
  - field: 'config.private_environment_config.connection_type'
  - field: 'config.private_environment_config.enable_private_endpoint'
  - field: 'config.private_environment_config.enable_privately_used_public_ips'
  - field: 'config.private_environment_config.master_ipv4_cidr_block'
  - field: 'config.private_environment_config.web_server_ipv4_cidr_block'
  - field: 'config.recovery_config.scheduled_snapshots_config.enabled'
  - field: 'config.recovery_config.scheduled_snapshots_config.snapshot_creation_schedule'
  - field: 'config.recovery_config.scheduled_snapshots_config.snapshot_location'
  - field: 'config.recovery_config.scheduled_snapshots_config.time_zone'
  - field: 'config.resilience_mode'
  - field: 'config.software_config.airflow_config_overrides'
  - field: 'config.software_config.cloud_data_lineage_integration.enabled'
  - field: 'config.software_config.env_variables'
  - field: 'config.software_config.image_version'
  - field: 'config.software_config.pypi_packages'
  - field: 'config.software_config.python_version'
  - field: 'config.software_config.scheduler_count'
  - field: 'config.software_config.web_server_plugins_mode'
  - field: 'config.web_server_config.machine_type'
  - field: 'config.web_server_network_access_control.allowed_ip_range.description'
  - field: 'config.web_server_network_access_control.allowed_ip_range.value'
  - field: 'config.workloads_config.dag_processor.count'
  - field: 'config.workloads_config.dag_processor.cpu'
  - field: 'config.workloads_config.dag_processor.memory_gb'
  - field: 'config.workloads_config.dag_processor.storage_gb'
  - field: 'config.workloads_config.scheduler.count'
  - field: 'config.workloads_config.scheduler.cpu'
  - field: 'config.workloads_config.scheduler.memory_gb'
  - field: 'config.workloads_config.scheduler.storage_gb'
  - field: 'config.workloads_config.triggerer.count'
  - field: 'config.workloads_config.triggerer.cpu'
  - field: 'config.workloads_config.triggerer.memory_gb'
  - field: 'config.workloads_config.web_server.cpu'
  - field: 'config.workloads_config.web_server.memory_gb'
  - field: 'config.workloads_config.web_server.storage_gb'
  - field: 'config.workloads_config.worker.cpu'
  - field: 'config.workloads_config.worker.max_count'
  - field: 'config.workloads_config.worker.memory_gb'
  - field: 'config.workloads_config.worker.min_count'
  - field: 'config.workloads_config.worker.storage_gb'
  - field: 'effective_labels'
    provider_only: true
  - field: 'labels'
  - field: 'name'
  - field: 'project'
  - field: 'region'
  - field: 'storage_config.bucket'
  - field: 'terraform_labels'
    provider_only: true
