# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

resource: 'google_os_config_os_policy_assignment'
generation_type: 'handwritten'
api_service_name: 'osconfig.googleapis.com'
api_version: 'v1'
api_resource_type_kind: 'OSPolicyAssignment'
fields:
  - field: 'baseline'
  - field: 'deleted'
  - field: 'description'
  - field: 'etag'
  - field: 'instance_filter.all'
  - field: 'instance_filter.exclusion_labels.labels'
  - field: 'instance_filter.inclusion_labels.labels'
  - field: 'instance_filter.inventories.os_short_name'
  - field: 'instance_filter.inventories.os_version'
  - field: 'location'
  - field: 'name'
  - field: 'os_policies.allow_no_resource_group_match'
  - field: 'os_policies.description'
  - field: 'os_policies.id'
  - field: 'os_policies.mode'
  - field: 'os_policies.resource_groups.inventory_filters.os_short_name'
  - field: 'os_policies.resource_groups.inventory_filters.os_version'
  - field: 'os_policies.resource_groups.resources.exec.enforce.args'
  - field: 'os_policies.resource_groups.resources.exec.enforce.file.allow_insecure'
  - field: 'os_policies.resource_groups.resources.exec.enforce.file.gcs.bucket'
  - field: 'os_policies.resource_groups.resources.exec.enforce.file.gcs.generation'
  - field: 'os_policies.resource_groups.resources.exec.enforce.file.gcs.object'
  - field: 'os_policies.resource_groups.resources.exec.enforce.file.local_path'
  - field: 'os_policies.resource_groups.resources.exec.enforce.file.remote.sha256_checksum'
  - field: 'os_policies.resource_groups.resources.exec.enforce.file.remote.uri'
  - field: 'os_policies.resource_groups.resources.exec.enforce.interpreter'
  - field: 'os_policies.resource_groups.resources.exec.enforce.output_file_path'
  - field: 'os_policies.resource_groups.resources.exec.enforce.script'
  - field: 'os_policies.resource_groups.resources.exec.validate.args'
  - field: 'os_policies.resource_groups.resources.exec.validate.file.allow_insecure'
  - field: 'os_policies.resource_groups.resources.exec.validate.file.gcs.bucket'
  - field: 'os_policies.resource_groups.resources.exec.validate.file.gcs.generation'
  - field: 'os_policies.resource_groups.resources.exec.validate.file.gcs.object'
  - field: 'os_policies.resource_groups.resources.exec.validate.file.local_path'
  - field: 'os_policies.resource_groups.resources.exec.validate.file.remote.sha256_checksum'
  - field: 'os_policies.resource_groups.resources.exec.validate.file.remote.uri'
  - field: 'os_policies.resource_groups.resources.exec.validate.interpreter'
  - field: 'os_policies.resource_groups.resources.exec.validate.output_file_path'
  - field: 'os_policies.resource_groups.resources.exec.validate.script'
  - field: 'os_policies.resource_groups.resources.file.content'
  - field: 'os_policies.resource_groups.resources.file.file.allow_insecure'
  - field: 'os_policies.resource_groups.resources.file.file.gcs.bucket'
  - field: 'os_policies.resource_groups.resources.file.file.gcs.generation'
  - field: 'os_policies.resource_groups.resources.file.file.gcs.object'
  - field: 'os_policies.resource_groups.resources.file.file.local_path'
  - field: 'os_policies.resource_groups.resources.file.file.remote.sha256_checksum'
  - field: 'os_policies.resource_groups.resources.file.file.remote.uri'
  - field: 'os_policies.resource_groups.resources.file.path'
  - field: 'os_policies.resource_groups.resources.file.permissions'
  - field: 'os_policies.resource_groups.resources.file.state'
  - field: 'os_policies.resource_groups.resources.id'
  - field: 'os_policies.resource_groups.resources.pkg.apt.name'
  - field: 'os_policies.resource_groups.resources.pkg.deb.pull_deps'
  - field: 'os_policies.resource_groups.resources.pkg.deb.source.allow_insecure'
  - field: 'os_policies.resource_groups.resources.pkg.deb.source.gcs.bucket'
  - field: 'os_policies.resource_groups.resources.pkg.deb.source.gcs.generation'
  - field: 'os_policies.resource_groups.resources.pkg.deb.source.gcs.object'
  - field: 'os_policies.resource_groups.resources.pkg.deb.source.local_path'
  - field: 'os_policies.resource_groups.resources.pkg.deb.source.remote.sha256_checksum'
  - field: 'os_policies.resource_groups.resources.pkg.deb.source.remote.uri'
  - field: 'os_policies.resource_groups.resources.pkg.desired_state'
  - field: 'os_policies.resource_groups.resources.pkg.googet.name'
  - field: 'os_policies.resource_groups.resources.pkg.msi.properties'
  - field: 'os_policies.resource_groups.resources.pkg.msi.source.allow_insecure'
  - field: 'os_policies.resource_groups.resources.pkg.msi.source.gcs.bucket'
  - field: 'os_policies.resource_groups.resources.pkg.msi.source.gcs.generation'
  - field: 'os_policies.resource_groups.resources.pkg.msi.source.gcs.object'
  - field: 'os_policies.resource_groups.resources.pkg.msi.source.local_path'
  - field: 'os_policies.resource_groups.resources.pkg.msi.source.remote.sha256_checksum'
  - field: 'os_policies.resource_groups.resources.pkg.msi.source.remote.uri'
  - field: 'os_policies.resource_groups.resources.pkg.rpm.pull_deps'
  - field: 'os_policies.resource_groups.resources.pkg.rpm.source.allow_insecure'
  - field: 'os_policies.resource_groups.resources.pkg.rpm.source.gcs.bucket'
  - field: 'os_policies.resource_groups.resources.pkg.rpm.source.gcs.generation'
  - field: 'os_policies.resource_groups.resources.pkg.rpm.source.gcs.object'
  - field: 'os_policies.resource_groups.resources.pkg.rpm.source.local_path'
  - field: 'os_policies.resource_groups.resources.pkg.rpm.source.remote.sha256_checksum'
  - field: 'os_policies.resource_groups.resources.pkg.rpm.source.remote.uri'
  - field: 'os_policies.resource_groups.resources.pkg.yum.name'
  - field: 'os_policies.resource_groups.resources.pkg.zypper.name'
  - field: 'os_policies.resource_groups.resources.repository.apt.archive_type'
  - field: 'os_policies.resource_groups.resources.repository.apt.components'
  - field: 'os_policies.resource_groups.resources.repository.apt.distribution'
  - field: 'os_policies.resource_groups.resources.repository.apt.gpg_key'
  - field: 'os_policies.resource_groups.resources.repository.apt.uri'
  - field: 'os_policies.resource_groups.resources.repository.goo.name'
  - field: 'os_policies.resource_groups.resources.repository.goo.url'
  - field: 'os_policies.resource_groups.resources.repository.yum.base_url'
  - field: 'os_policies.resource_groups.resources.repository.yum.display_name'
  - field: 'os_policies.resource_groups.resources.repository.yum.gpg_keys'
  - field: 'os_policies.resource_groups.resources.repository.yum.id'
  - field: 'os_policies.resource_groups.resources.repository.zypper.base_url'
  - field: 'os_policies.resource_groups.resources.repository.zypper.display_name'
  - field: 'os_policies.resource_groups.resources.repository.zypper.gpg_keys'
  - field: 'os_policies.resource_groups.resources.repository.zypper.id'
  - field: 'project'
  - field: 'reconciling'
  - field: 'revision_create_time'
  - field: 'revision_id'
  - field: 'rollout.disruption_budget.fixed'
  - field: 'rollout.disruption_budget.percent'
  - field: 'rollout.min_wait_duration'
  - field: 'rollout_state'
  - field: 'skip_await_rollout'
  - field: 'uid'
