resource: 'google_os_config_patch_deployment'
generation_type: 'mmv1'
source_file: 'products/osconfig/PatchDeployment.yaml'
api_service_name: 'osconfig.googleapis.com'
api_version: 'v1'
api_resource_type_kind: 'PatchDeployment'
fields:
  - field: 'create_time'
  - field: 'description'
  - field: 'duration'
  - field: 'instance_filter.all'
  - field: 'instance_filter.group_labels.labels'
  - field: 'instance_filter.instance_name_prefixes'
  - field: 'instance_filter.instances'
  - field: 'instance_filter.zones'
  - field: 'last_execute_time'
  - field: 'name'
  - field: 'one_time_schedule.execute_time'
  - field: 'patch_config.apt.excludes'
  - field: 'patch_config.apt.exclusive_packages'
  - field: 'patch_config.apt.type'
  - field: 'patch_config.goo.enabled'
  - field: 'patch_config.mig_instances_allowed'
  - field: 'patch_config.post_step.linux_exec_step_config.allowed_success_codes'
  - field: 'patch_config.post_step.linux_exec_step_config.gcs_object.bucket'
  - field: 'patch_config.post_step.linux_exec_step_config.gcs_object.generation_number'
  - field: 'patch_config.post_step.linux_exec_step_config.gcs_object.object'
  - field: 'patch_config.post_step.linux_exec_step_config.interpreter'
  - field: 'patch_config.post_step.linux_exec_step_config.local_path'
  - field: 'patch_config.post_step.windows_exec_step_config.allowed_success_codes'
  - field: 'patch_config.post_step.windows_exec_step_config.gcs_object.bucket'
  - field: 'patch_config.post_step.windows_exec_step_config.gcs_object.generation_number'
  - field: 'patch_config.post_step.windows_exec_step_config.gcs_object.object'
  - field: 'patch_config.post_step.windows_exec_step_config.interpreter'
  - field: 'patch_config.post_step.windows_exec_step_config.local_path'
  - field: 'patch_config.pre_step.linux_exec_step_config.allowed_success_codes'
  - field: 'patch_config.pre_step.linux_exec_step_config.gcs_object.bucket'
  - field: 'patch_config.pre_step.linux_exec_step_config.gcs_object.generation_number'
  - field: 'patch_config.pre_step.linux_exec_step_config.gcs_object.object'
  - field: 'patch_config.pre_step.linux_exec_step_config.interpreter'
  - field: 'patch_config.pre_step.linux_exec_step_config.local_path'
  - field: 'patch_config.pre_step.windows_exec_step_config.allowed_success_codes'
  - field: 'patch_config.pre_step.windows_exec_step_config.gcs_object.bucket'
  - field: 'patch_config.pre_step.windows_exec_step_config.gcs_object.generation_number'
  - field: 'patch_config.pre_step.windows_exec_step_config.gcs_object.object'
  - field: 'patch_config.pre_step.windows_exec_step_config.interpreter'
  - field: 'patch_config.pre_step.windows_exec_step_config.local_path'
  - field: 'patch_config.reboot_config'
  - field: 'patch_config.windows_update.classifications'
  - field: 'patch_config.windows_update.excludes'
  - field: 'patch_config.windows_update.exclusive_patches'
  - field: 'patch_config.yum.excludes'
  - field: 'patch_config.yum.exclusive_packages'
  - field: 'patch_config.yum.minimal'
  - field: 'patch_config.yum.security'
  - field: 'patch_config.zypper.categories'
  - field: 'patch_config.zypper.excludes'
  - field: 'patch_config.zypper.exclusive_patches'
  - field: 'patch_config.zypper.severities'
  - field: 'patch_config.zypper.with_optional'
  - field: 'patch_config.zypper.with_update'
  - field: 'patch_deployment_id'
    provider_only: true
  - field: 'recurring_schedule.end_time'
  - field: 'recurring_schedule.last_execute_time'
  - field: 'recurring_schedule.monthly.month_day'
  - field: 'recurring_schedule.monthly.week_day_of_month.day_of_week'
  - field: 'recurring_schedule.monthly.week_day_of_month.day_offset'
  - field: 'recurring_schedule.monthly.week_day_of_month.week_ordinal'
  - field: 'recurring_schedule.next_execute_time'
  - field: 'recurring_schedule.start_time'
  - field: 'recurring_schedule.time_of_day.hours'
  - field: 'recurring_schedule.time_of_day.minutes'
  - field: 'recurring_schedule.time_of_day.nanos'
  - field: 'recurring_schedule.time_of_day.seconds'
  - field: 'recurring_schedule.time_zone.id'
  - field: 'recurring_schedule.time_zone.version'
  - field: 'recurring_schedule.weekly.day_of_week'
  - field: 'rollout.disruption_budget.fixed'
  - field: 'rollout.disruption_budget.percentage'
    api_field: 'rollout.disruption_budget.percent'
  - field: 'rollout.mode'
  - field: 'update_time'
