resource: google_certificate_manager_certificate_issuance_config
generation_type: mmv1
source_file: products/certificatemanager/CertificateIssuanceConfig.yaml
api_service_name: certificatemanager.googleapis.com
api_version: v1
api_resource_type_kind: CertificateIssuanceConfig
fields:
    - api_field: certificateAuthorityConfig.certificateAuthorityServiceConfig.caPool
    - api_field: createTime
    - api_field: description
    - field: effective_labels
      provider_only: true
    - api_field: keyAlgorithm
    - api_field: labels
    - api_field: lifetime
    - field: location
      provider_only: true
    - field: name
      provider_only: true
    - api_field: rotationWindowPercentage
    - field: terraform_labels
      provider_only: true
    - api_field: updateTime
