resource: 'google_firebase_app_check_service_config'
generation_type: 'mmv1'
api_service_name: 'firebaseappcheck.googleapis.com'
api_version: 'v1'
api_resource_type_kind: 'Service'
fields:
  - field: 'enforcement_mode'
  - field: 'name'
  - field: 'service_id'
    provider_only: true
