resource: google_firebase_app_check_recaptcha_v3_config
generation_type: mmv1
source_file: products/firebaseappcheck/RecaptchaV3Config.yaml
api_service_name: firebaseappcheck.googleapis.com
api_version: v1
api_resource_type_kind: RecaptchaConfig
api_variant_patterns:
    - projects/{project}/apps/{app}/recaptchaV3Config
fields:
    - field: app_id
      provider_only: true
    - api_field: name
    - api_field: siteSecret
    - api_field: siteSecretSet
    - api_field: tokenTtl
