resource: google_firebase_app_check_device_check_config
generation_type: mmv1
source_file: products/firebaseappcheck/DeviceCheckConfig.yaml
api_service_name: firebaseappcheck.googleapis.com
api_version: v1
api_resource_type_kind: DeviceCheckConfig
fields:
    - field: app_id
      provider_only: true
    - api_field: keyId
    - api_field: name
    - api_field: privateKey
    - api_field: privateKeySet
    - api_field: tokenTtl
