name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

env:
  GOPROXY: https://proxy.golang.org/
  PROTOCOL_VERSION: "5.0"
  PROTOCOL_VERSIONS: "5.0"
  SIGNER: interim_signing_subkey_7685B676

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Read go version
        id: go-version
        run: |
          content=`cat ./.go-version`
          echo "::set-output name=content::$content"
      - uses: actions/setup-go@v2
        with:
          # TODO: Replace with go-version-from-file when it is supported
          # https://github.com/actions/setup-go/pull/62
          go-version: ${{ steps.go-version.outputs.content }}
      - name: Setup hc-releases
        uses: hashicorp/setup-hc-releases@v2
        with:
          github-token: ${{ secrets.HASHI_RELEASES_GITHUB_TOKEN }}
      - uses: hashicorp/setup-signore@v2
        with:
          github-token: ${{ secrets.HASHI_SIGNORE_GITHUB_TOKEN }}
          signer: interim_signing_subkey_768B676
      - name: Release Notes
        run: sed -n -e "1{/# /d;}" -e "2{/^$/d;}" -e "/# \[$(git describe --abbrev=0 --exclude="$(git describe --abbrev=0 --match='v*.*.*' --tags)" --match='v*.*.*' --tags | tr -d v)/q;p" CHANGELOG.md > /tmp/RELEASE-NOTES.md
      - name: goreleaser release
        uses: goreleaser/goreleaser-action@v2
        with:
          args: release --release-notes /tmp/RELEASE-NOTES.md --rm-dist
        env:
          HC_RELEASES_HOST: ${{ secrets.HC_RELEASES_HOST_STAGING }}
          HC_RELEASES_KEY: ${{ secrets.HC_RELEASES_KEY_STAGING }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SIGNORE_CLIENT_ID: ${{ secrets.SIGNORE_CLIENT_ID }}
          SIGNORE_CLIENT_SECRET: ${{ secrets.SIGNORE_CLIENT_SECRET }}
      - name: Create Release metadata
        uses: hashicorp/actions-hc-releases-create-metadata@v1
        with:
          private-tools-token: ${{ secrets.CODESIGN_GITHUB_TOKEN }}
          product-name: "terraform-provider-google"
          version: ${{ github.ref_name }}
          hc-releases-host: ${{ secrets.HC_RELEASES_HOST_STAGING}}
          hc-releases-key: ${{ secrets.HC_RELEASES_KEY_STAGING }}
      - name: Promote
        uses: hashicorp/actions-hc-releases-promote@v1
        with:
          product-name: "terraform-provider-google"
          version: ${{ github.ref_name }}
          hc-releases-host: ${{ secrets.HC_RELEASES_HOST_PROD }}
          hc-releases-key: ${{ secrets.HC_RELEASES_KEY_PROD }}
          hc-releases-source_env_key: ${{ secrets.HC_RELEASES_KEY_STAGING }}
