resource: google_apphub_application
generation_type: mmv1
source_file: products/apphub/Application.yaml
api_service_name: apphub.googleapis.com
api_version: v1
api_resource_type_kind: Application
autogen_status: true
fields:
    - field: application_id
      provider_only: true
    - api_field: attributes.businessOwners.displayName
    - api_field: attributes.businessOwners.email
    - api_field: attributes.criticality.type
    - api_field: attributes.developerOwners.displayName
    - api_field: attributes.developerOwners.email
    - api_field: attributes.environment.type
    - api_field: attributes.operatorOwners.displayName
    - api_field: attributes.operatorOwners.email
    - api_field: createTime
    - api_field: description
    - api_field: displayName
    - field: location
      provider_only: true
    - api_field: name
    - api_field: scope.type
    - api_field: state
    - api_field: uid
    - api_field: updateTime
